### ISSUE TITLE
model release 

### ISSUE THREAD

**Issue by songtaoshi** [pirxus/personalVAD#1]
Hi, @pirxus  really kind of shared implementation,   
It would be great to user if you could share the checkpoint for fast evaluation.

**Comment by pirxus** [comment]
Hi @songtaoshi :) thank you for the heads up, somehow I had forgotten to publish the models when handing in my thesis... For now, I added a link to the readme file (under the Instructions section), which will download an ~800MB archive containing all the trained models and some sample evaluation data. That version of the repository is the reference one for the readme file so everything should work. I am aware that this is very much not the ideal solution and will be restructuring the repository in the near future to make these things more comfortable for everyone interested..

**Comment by songtaoshi** [comment]
Hi @pirxus, have you tried your own model using your voice and your real conversation.   
I make my voice embedding and make a conversation with other people, but the result seems not work.   

So I am asking wether you have tried your real case just using your released model.  (I have successfully reproduce using your generated test data)

**Comment by pirxus** [comment]
Hi, I actually have not - partly because I am not a native english speaker. 

However (and I'm sorry to disappoint you if these were your intentions), please bear in mind that this project is not meant to be used in production and is probably going to fail in most real-life scenarios. It would first be necessary to train the VADs on at least some real-world conversation data, which is very hard to obtain in the quantities necessary, at least it was for me at the time of working on this project.

In my opinion, this method shows some promise overall but there are quite a few things that would need to be improved and tested before it can be decided whether or not it actually works satisfyingly enough :)

I would suggest you try one of the more heavyweight models such as the `vad_set_tanh_score1_10ep.pt` model. If any of the models were to give you some positive results, it would be this one.

Additionally, if you were able to- and of course willing - you could send me  the recordings of yourself that you used for the experiment and let me try and obtain some results and maybe some useful information about why the models do not detect your speech properly :)

**Comment by songtaoshi** [comment]
@pirxus really thanks for your reply, actually I just try the Chinese. I just make the experiment to see whether it can work in real scenario.   I send my audio to your email?

**Comment by songtaoshi** [comment]
it's really hard to say whether it can work, so I think it's necessary to make the try.

**Comment by pirxus** [comment]
Sure, just send it to my inbox.. :) however, I'm quite skeptical it'll work for the Chinese language unfortunately..

**Comment by songtaoshi** [comment]
Hi @pirxus  have you receive my audio.  Hhhhh

**Comment by pirxus** [comment]
Yep, thanks, got them, I'll do some testing and will get back to you afterwards.

**Comment by songtaoshi** [comment]
Thanks a lot, and I also think you can try your voice. Hhhhh, maybe magic happens.

**Comment by songtaoshi** [comment]
@pirxus hi, how about the result ：）

**Comment by pirxus** [comment]
Hi, so unfortunately, I had no success with the recordings. But at the same time, I realized that the target speaker audio is in the m4a format, sampled at 48kHz when it should be a wav at 16kHz. Did you perform any conversion on this source audio? Also, the conversation audio is full of strange glitchy sounds, almost as if it had been cut up and put back together, creating some concatenation artifacts or something like that.

But again, I have to reiterate, I very much doubt one can get more than a few correctly classified frames here and there when running the models on the Chinese language.. Maybe ask an English-speaking friend to record some things for you and compare the results? :)

**Comment by songtaoshi** [comment]
really thanks for your reply!    
1. the sample rate I resample to 16k Hz, I think it should make much impact.    
2. the conversation is recorded in streaming and concatenated in numpy array, maybe it's the source of concatenation artifacts    

I notice there is an important description in the paper "distill the embedding net into the small vad net", so it may not sufficient just using the limited mix of libri dataset since our embedding network need voxceleb2 such a large dataset to work in real-scenario.   

BTW, do you have a wechat, we can discuss and cooperate  in time ：） my wechat number is 914193897
